# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23717aa9c87de1fb509934d4c62cbab54773daebda11a13e19b4f0d9cccf7c31807845d5454cd07be33f277e73559741af14686cf3e0aec58d6e077f14c4a69
  stripe_publishable_key: pk_test_aDDRtNbVMZtHeMQkGWLTqXfc
  stripe_secret_key: sk_test_Vc1ceLIaZaq3oH6kDanXGB0v

test:
  secret_key_base: 8ab737b89985287d2933bf71622db56cf8f5420ffdcd98bcab72b301cba65682d31ac1aae6b34cfb91ea8f224b88bf1f857561d8be6f5db441afd71c922a84d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']


  