source 'https://rubygems.org'

#ruby '2.1.5'

gem 'rails', '4.1.2'
gem 'mysql2'
gem 'devise', '3.2.4'
gem 'email_validator'     

gem 'uglifier', '>= 1.3.0'
gem 'sass-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.0'

gem 'turbolinks'
gem 'jquery-rails'

gem "pdfkit"
gem 'geocoder'
gem 'simple_form'
gem "nested_form"
gem 'wkhtmltopdf-binary'
gem 'therubyracer'

gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development
gem 'quiet_assets', group: :development
gem 'aescrypt'
gem 'apns'
gem 'em-websocket'
gem 'grocer'
gem 's3_direct_upload'
#pay
gem 'stripe'
gem 'geokit'
gem "google_custom_search_api"

